'use client';

import React, {useState} from 'react';
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarProvider,
  SidebarSeparator,
  SidebarTrigger,
} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {ModeToggle} from '@/components/mode-toggle';
import {DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger} from "@/components/ui/dropdown-menu";
import {Avatar, AvatarFallback, AvatarImage} from "@/components/ui/avatar";
import {Icons} from "@/components/icons";
import {Textarea} from "@/components/ui/textarea";
import {generateHint} from "@/ai/flows/generate-hints";
import {useToast} from "@/hooks/use-toast";
import {Input} from "@/components/ui/input";
import {Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle} from "@/components/ui/card";
import {Accordion, AccordionContent, AccordionItem, AccordionTrigger} from "@/components/ui/accordion";
import {RadioGroup, RadioGroupItem} from "@/components/ui/radio-group";
import {Label} from "@/components/ui/label";

const chapters = [
  {
    id: '1',
    title: 'Math - Number Systems',
    category: 'Math',
    type: 'Normal',
    explanation: 'Understanding different types of numbers and their properties.',
    questions: [
      {
        id: '1',
        text: 'What is the sum of all prime numbers between 10 and 20?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['50', '60', '70', '80'],
        correctAnswer: '60',
        gradeLevel: 5,
      },
      {
        id: '2',
        text: 'Which of the following is a composite number?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '3', '5', '9'],
        correctAnswer: '9',
        gradeLevel: 4,
      },
      {
        id: '3',
        text: 'What is the value of pi to two decimal places?',
        category: 'Math',
        type: 'free-form',
        correctAnswer: '3.14',
        gradeLevel: 5,
      },
      {
        id: '4',
        text: 'Solve for x: 2x + 5 = 15',
        category: 'Math',
        type: 'multiple-choice',
        options: ['x = 2', 'x = 5', 'x = 10', 'x = 20'],
        correctAnswer: 'x = 5',
        gradeLevel: 4,
      },
      {
        id: '5',
        text: 'Simplify: 3(a + 2b) - a + b',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2a + 7b', '3a + 6b', '4a + 8b', '5a + 9b'],
        correctAnswer: '2a + 7b',
        gradeLevel: 5,
      },
      {
        id: '6',
        text: 'If x = 3 and y = 4, what is the value of x^2 + y^2?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['7', '14', '25', '49'],
        correctAnswer: '25',
        gradeLevel: 5,
      },
      {
        id: '7',
        text: 'What is the next prime number after 23?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['24', '25', '27', '29'],
        correctAnswer: '29',
        gradeLevel: 4,
      },
      {
        id: '8',
        text: 'Calculate: 15% of 200',
        category: 'Math',
        type: 'multiple-choice',
        options: ['15', '20', '30', '45'],
        correctAnswer: '30',
        gradeLevel: 5,
      },
      {
        id: '9',
        text: 'What is the square root of 144?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['10', '12', '14', '16'],
        correctAnswer: '12',
        gradeLevel: 4,
      },
      {
        id: '10',
        text: 'If a train travels 120 miles in 2 hours, what is its average speed?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['40', '50', '60', '70'],
        correctAnswer: '60',
        gradeLevel: 5,
      },
      {
        id: '11',
        text: 'Solve for y: 3y - 7 = 14',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '7',
        gradeLevel: 4,
      },
      {
        id: '12',
        text: 'What is the area of a circle with a radius of 7?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['154', '22', '44', '49'],
        correctAnswer: '154',
        gradeLevel: 5,
      },
      {
        id: '13',
        text: 'What is 7 cubed?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['21', '49', '243', '343'],
        correctAnswer: '343',
        gradeLevel: 5,
      },
      {
        id: '14',
        text: 'If 5x = 35, then x = ?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '7',
        gradeLevel: 4,
      },
      {
        id: '15',
        text: 'What is the value of 10! (10 factorial)?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3628800', '362800', '362880', '36288000'],
        correctAnswer: '3628800',
        gradeLevel: 5,
      },
      {
        id: '16',
        text: 'Solve for z: z/4 + 8 = 12',
        category: 'Math',
        type: 'multiple-choice',
        options: ['4', '8', '12', '16'],
        correctAnswer: '16',
        gradeLevel: 4,
      },
      {
        id: '17',
        text: 'What is the circumference of a circle with diameter 28?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['22', '44', '88', '176'],
        correctAnswer: '88',
        gradeLevel: 5,
      },
      {
        id: '18',
        text: 'What is the value of the expression 4^3 - 3^4?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['-17', '17', '0', '1'],
        correctAnswer: '-17',
        gradeLevel: 5,
      },
      {
        id: '19',
        text: 'If you deposit $500 in a savings account with an annual interest rate of 5%, how much interest will you earn in one year?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$5', '$15', '$25', '$50'],
        correctAnswer: '$25',
        gradeLevel: 5,
      },
      {
        id: '20',
        text: 'A store sells a product for $45, which includes a 20% markup. What was the original cost of the product?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$36', '$37.5', '$40', '$42.5'],
        correctAnswer: '$37.5',
        gradeLevel: 5,
      },
      {
        id: '21',
        text: 'What is the result of (3 + 5) × 2 - 8 ÷ 4?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['10', '12', '14', '16'],
        correctAnswer: '14',
        gradeLevel: 5,
      },
      {
        id: '22',
        text: 'If two angles of a triangle measure 60° and 80°, what is the measure of the third angle?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['20', '30', '40', '50'],
        correctAnswer: '40',
        gradeLevel: 4,
      },
      {
        id: '23',
        text: 'Calculate 25 ÷ 0.5 + 10 × 3 - 20',
        category: 'Math',
        type: 'multiple-choice',
        options: ['50', '60', '70', '80'],
        correctAnswer: '60',
        gradeLevel: 5,
      },
      {
        id: '24',
        text: 'If one side of a square is 9 cm, what is its area?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['36', '63', '72', '81'],
        correctAnswer: '81',
        gradeLevel: 4,
      },
      {
        id: '25',
        text: 'If a circle has a radius of 6 meters, what is its area?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['28.26', '36', '37.68', '113.1'],
        correctAnswer: '113.1',
        gradeLevel: 5,
      },
      {
        id: '26',
        text: 'A bag contains 3 red marbles, 4 blue marbles, and 5 green marbles. What is the probability of picking a blue marble?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['0.25', '0.333', '0.416', '0.5'],
        correctAnswer: '0.333',
        gradeLevel: 5,
      },
      {
        id: '27',
        text: 'What is the volume of a cube with each side measuring 4 inches?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['12', '16', '32', '64'],
        correctAnswer: '64',
        gradeLevel: 4,
      },
      {
        id: '28',
        text: 'If the perimeter of a rectangle is 30 cm and its length is 10 cm, what is its width?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '4', '5', '6'],
        correctAnswer: '5',
        gradeLevel: 5,
      },
      {
        id: '29',
        text: 'A car travels at a speed of 80 km/h. How long does it take to travel 400 km?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '4', '5', '6'],
        correctAnswer: '5',
        gradeLevel: 5,
      },
      {
        id: '30',
        text: 'What is the next number in the sequence: 2, 6, 12, 20, ?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['24', '28', '30', '32'],
        correctAnswer: '30',
        gradeLevel: 4,
      },
      {
        id: '31',
        text: 'Find the value of x in the equation 4x + 2 = 18',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '3', '4', '5'],
        correctAnswer: '4',
        gradeLevel: 4,
      },
      {
        id: '32',
        text: 'If 3 notebooks cost $6.75, how much does one notebook cost?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$2.00', '$2.25', '$2.50', '$2.75'],
        correctAnswer: '$2.25',
        gradeLevel: 5,
      },
      {
        id: '33',
        text: 'What is the area of a triangle with base 12 cm and height 8 cm?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['24', '48', '96', '192'],
        correctAnswer: '48',
        gradeLevel: 5,
      },
      {
        id: '34',
        text: 'If a person saves $150 each month, how much will they save in 2 years?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$1800', '$2400', '$3000', '$3600'],
        correctAnswer: '$3600',
        gradeLevel: 5,
      },
      {
        id: '35',
        text: 'What is the sum of the first 10 positive integers?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['45', '50', '55', '60'],
        correctAnswer: '55',
        gradeLevel: 5,
      },
      {
        id: '36',
        text: 'A discount of 15% is applied to a dress that costs $80. What is the sale price?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$60', '$64', '$68', '$72'],
        correctAnswer: '$68',
        gradeLevel: 5,
      },
      {
        id: '37',
        text: 'What is the value of (-3)^3?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['-27', '-9', '9', '27'],
        correctAnswer: '-27',
        gradeLevel: 5,
      },
      {
        id: '38',
        text: 'Convert 45% to a fraction in simplest form',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3/5', '9/20', '1/2', '1/45'],
        correctAnswer: '9/20',
        gradeLevel: 5,
      },
      {
        id: '39',
        text: 'If a student scores 75 out of 125 on a test, what percentage did they get?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['50', '55', '60', '65'],
        correctAnswer: '60',
        gradeLevel: 5,
      },
      {
        id: '40',
        text: 'What is the product of 0.6 and 0.8?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['0.14', '0.48', '4.8', '48'],
        correctAnswer: '0.48',
        gradeLevel: 5,
      },
      {
        id: '41',
        text: 'A train leaves Station A at 6:00 AM and arrives at Station B at 11:30 AM. If the distance between the stations is 460 km, what is the average speed of the train?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['73.64', '80.23', '83.64', '92'],
        correctAnswer: '83.64',
        gradeLevel: 5,
      },
      {
        id: '42',
        text: 'A phone is listed for $600 and is discounted by 30%. A sales tax of 8% is then added. What is the final price?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['360.24', '400', '462.24', '500'],
        correctAnswer: '462.24',
        gradeLevel: 5,
      },
      {
        id: '43',
        text: 'You drive from home at an average speed of 60 mph and arrive in 3 hours. How far do you drive?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['120', '160', '180', '200'],
        correctAnswer: '180',
        gradeLevel: 5,
      },
      {
        id: '44',
        text: 'You have a cylindrical tank with a radius of 3 meters and a height of 8 meters. What is its volume?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['226.19', '340', '400', '120'],
        correctAnswer: '226.19',
        gradeLevel: 5,
      },
      {
        id: '45',
        text: 'A recipe requires 2 cups of flour for every 3 eggs. If you want to use 9 eggs, how many cups of flour do you need?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '6',
        gradeLevel: 5,
      },
      {
        id: '46',
        text: 'Find the perimeter of a square garden with an area of 625 square feet.',
        category: 'Math',
        type: 'multiple-choice',
        options: ['25', '50', '75', '100'],
        correctAnswer: '100',
        gradeLevel: 5,
      },
      {
        id: '47',
        text: 'You invest $3000 in a fund that promises a return of 6% compounded annually. How much money will you have after 5 years?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3900', '4014.68', '4100', '4200'],
        correctAnswer: '4014.68',
        gradeLevel: 5,
      },
      {
        id: '48',
        text: 'Solve for x: 7x − 5 = 3x + 15',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '4', '5', '6'],
        correctAnswer: '5',
        gradeLevel: 5,
      },
      {
        id: '49',
        text: 'Calculate: 100 - (45 + 32)',
        category: 'Math',
        type: 'multiple-choice',
        options: ['13', '23', '33', '43'],
        correctAnswer: '23',
        gradeLevel: 5,
      },
      {
        id: '50',
        text: 'Find the value of y: 6y + 3(2y − 1) = 9',
        category: 'Math',
        type: 'multiple-choice',
        options: ['1', '2', '3', '4'],
        correctAnswer: '1',
        gradeLevel: 5,
      },
      {
        id: '51',
        text: 'Calculate the percentage increase: Old Value = 200, New Value = 250',
        category: 'Math',
        type: 'multiple-choice',
        options: ['15', '20', '25', '30'],
        correctAnswer: '25',
        gradeLevel: 5,
      },
      {
        id: '52',
        text: 'Find the LCM of 12 and 18',
        category: 'Math',
        type: 'multiple-choice',
        options: ['24', '36', '48', '60'],
        correctAnswer: '36',
        gradeLevel: 5,
      },
      {
        id: '53',
        text: 'Simplify: (4^5) / (4^2)',
        category: 'Math',
        type: 'multiple-choice',
        options: ['4', '8', '16', '64'],
        correctAnswer: '64',
        gradeLevel: 5,
      },
      {
        id: '54',
        text: 'A store offers a 25% discount on a camera listed at $300. What is the sale price?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['200', '225', '250', '275'],
        correctAnswer: '225',
        gradeLevel: 5,
      },
      {
        id: '55',
        text: 'What is the probability of rolling a 4 on a 6-sided die?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['1/2', '1/3', '1/4', '1/6'],
        correctAnswer: '1/6',
        gradeLevel: 5,
      },
      {
        id: '56',
        text: 'A ladder leans against a wall, forming a right triangle. The ladder is 15 feet long, and the base of the ladder is 9 feet from the wall. How high up the wall does the ladder reach?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['10', '11', '12', '13'],
        correctAnswer: '12',
        gradeLevel: 5,
      },
      {
        id: '57',
        text: 'The measure of each angle in a regular pentagon',
        category: 'Math',
        type: 'multiple-choice',
        options: ['90', '108', '120', '135'],
        correctAnswer: '108',
        gradeLevel: 5,
      },
      {
        id: '58',
        text: 'Simplify: (6x^3 + 9x^2) / (3x)',
        category: 'Math',
        type: 'multiple-choice',
        options: ['x^2+x', '2x^2+3x', '4x+x', '9x^2'],
        correctAnswer: '2x^2+3x',
        gradeLevel: 5,
      },
      {
        id: '59',
        text: 'You are planning a rectangular garden that is twice as long as it is wide. If you have 42 feet of fencing, what are the dimensions of your garden?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3,6', '5,10', '7, 14', '9,18'],
        correctAnswer: '7, 14',
        gradeLevel: 5,
      },
      {
        id: '60',
        text: 'The diameter of the wheel is 14inches what is the circumference?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['22', '33', '44', '55'],
        correctAnswer: '44',
        gradeLevel: 5,
      },
      {
        id: '61',
        text: 'What is 11% of 1100?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['11', '21', '121', '131'],
        correctAnswer: '121',
        gradeLevel: 5,
      },
      {
        id: '62',
        text: 'Solve for a : 4a/3 = 16',
        category: 'Math',
        type: 'multiple-choice',
        options: ['8', '9', '10', '12'],
        correctAnswer: '12',
        gradeLevel: 5,
      },
      {
        id: '63',
        text: '5^6 divided by 5^4',
        category: 'Math',
        type: 'multiple-choice',
        options: ['5', '15', '25', '35'],
        correctAnswer: '25',
        gradeLevel: 5,
      },
      {
        id: '64',
        text: 'Express as a decimal 9/20',
        category: 'Math',
        type: 'multiple-choice',
        options: ['0.25', '0.35', '0.45', '0.55'],
        correctAnswer: '0.45',
        gradeLevel: 5,
      },
      {
        id: '65',
        text: 'What is the sum of interior angles of a triangle?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['90', '180', '270', '360'],
        correctAnswer: '180',
        gradeLevel: 5,
      },
      {
        id: '66',
        text: 'You borrow $5000 at an annual interest rate of 8%. What is the simple interest due after 3 years?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$400', '$800', '$1200', '$1600'],
        correctAnswer: '1200',
        gradeLevel: 5,
      },
      {
        id: '67',
        text: 'What is the average of 2, 8, 15, and 21?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['9.5', '10.5', '11.5', '12.5'],
        correctAnswer: '11.5',
        gradeLevel: 5,
      },
      {
        id: '68',
        text: 'Calculate the value of 4! + 3! - 2!',
        category: 'Math',
        type: 'multiple-choice',
        options: ['24', '26', '28', '30'],
        correctAnswer: '28',
        gradeLevel: 5,
      },
      {
        id: '69',
        text: 'What is the HCF of 36 and 48',
        category: 'Math',
        type: 'multiple-choice',
        options: ['6', '8', '10', '12'],
        correctAnswer: '12',
        gradeLevel: 5,
      },
      {
        id: '70',
        text: 'Find the missing term in the series: 1, 4, 9, 16, ?, 36',
        category: 'Math',
        type: 'multiple-choice',
        options: ['15', '20', '25', '30'],
        correctAnswer: '25',
        gradeLevel: 5,
      },
      {
        id: '71',
        text: 'The base of an isosceles triangle is 8cm and its perimeter is 28cm. Find the length of each of the equal sides',
        category: 'Math',
        type: 'multiple-choice',
        options: ['7', '8', '9', '10'],
        correctAnswer: '10',
        gradeLevel: 5,
      },
      {
        id: '72',
        text: 'Which is bigger 2^8 or 3^5',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2^8', '3^5', 'Equal', 'Cannot be compared'],
        correctAnswer: '3^5',
        gradeLevel: 5,
      },
      {
        id: '73',
        text: 'If the area of a circle is 49π sq. cm, find its circumference',
        category: 'Math',
        type: 'multiple-choice',
        options: ['7π', '14π', '21π', '28π'],
        correctAnswer: '14π',
        gradeLevel: 5,
      },
      {
        id: '74',
        text: 'What is a googol?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['10^10', '10^50', '10^100', '10^1000'],
        correctAnswer: '10^100',
        gradeLevel: 5,
      },
      {
        id: '75',
        text: 'Solve for x, |x - 5| = 3',
        category: 'Math',
        type: 'multiple-choice',
        options: ['0, 5', '1, 9', '2, 8', '3, 7'],
        correctAnswer: '2, 8',
        gradeLevel: 5,
      },
      {
        id: '76',
        text: 'Find the next number in this series 19, 23, 29, 31, 37, ?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['38', '39', '40', '41'],
        correctAnswer: '41',
        gradeLevel: 5,
      },
      {
        id: '77',
        text: 'The ratio of two numbers is 5:6. If the sum of the numbers is 55, find the numbers.',
        category: 'Math',
        type: 'multiple-choice',
        options: ['20, 35', '22, 33', '25, 30', '26, 29'],
        correctAnswer: '25, 30',
        gradeLevel: 5,
      },
      {
        id: '78',
        text: 'If a dozen apples cost $18, how much will 5 apples cost?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$5.5', '$6.5', '$7.5', '$8.5'],
        correctAnswer: '$7.5',
        gradeLevel: 5,
      },
      {
        id: '79',
        text: 'Express 0.36 as a fraction in the lowest form',
        category: 'Math',
        type: 'multiple-choice',
        options: ['9/25', '10/25', '11/25', '12/25'],
        correctAnswer: '9/25',
        gradeLevel: 5,
      },
      {
        id: '80',
        text: 'What is the number of diagonals in a heptagon?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['12', '13', '14', '15'],
        correctAnswer: '14',
        gradeLevel: 5,
      },
      {
        id: '81',
        text: 'What is 150% of 70?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['95', '100', '105', '110'],
        correctAnswer: '105',
        gradeLevel: 5,
      },
      {
        id: '82',
        text: 'Solve for c : c/5 + 7 = 12',
        category: 'Math',
        type: 'multiple-choice',
        options: ['15', '20', '25', '30'],
        correctAnswer: '25',
        gradeLevel: 5,
      },
      {
        id: '83',
        text: 'If log 100 = x, what is x?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['0', '1', '2', '3'],
        correctAnswer: '2',
        gradeLevel: 5,
      },
      {
        id: '84',
        text: 'What are twin primes?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['Prime that differ by 1', 'Primes that differ by 2', 'Prime that differ by 3', 'Prime that differ by 4'],
        correctAnswer: 'Primes that differ by 2',
        gradeLevel: 5,
      },
      {
        id: '85',
        text: 'A watch loses 5 minutes every hour. How many hours will it take for the watch to lose 1 hour?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['11', '12', '13', '14'],
        correctAnswer: '12',
        gradeLevel: 5,
      },
      {
        id: '86',
        text: 'A rectangle is 10 cms long and 6 cms wide. If the length is reduced by 2 cm and width increased by 2 cms, by what amount will the area change?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['Increase by 4', 'Decrease by 4', 'No Change', 'Increase by 6'],
        correctAnswer: 'No Change',
        gradeLevel: 5,
      },
      {
        id: '87',
        text: 'What is a perfect number?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['Number divisible by 3', 'Sum of divisors equals the number', 'Sum of divisors less than the number', 'A prime number'],
        correctAnswer: 'Sum of divisors equals the number',
        gradeLevel: 5,
      },
      {
        id: '88',
        text: 'The angles of a quadrilateral are in the ratio 3:5:9:13. Find the measure of the largest angle',
        category: 'Math',
        type: 'multiple-choice',
        options: ['150', '153', '156', '159'],
        correctAnswer: '156',
        gradeLevel: 5,
      },
      {
        id: '89',
        text: 'When is Pi day celebrated?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['March 14', 'April 14', 'May 14', 'June 14'],
        correctAnswer: 'March 14',
        gradeLevel: 5,
      },
      {
        id: '90',
        text: 'What is a Mersenne Prime?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['Prime of the form 2^n - 1', 'Prime of the form 2^n', 'Prime of the form 2^n + 1', 'Even Prime'],
        correctAnswer: 'Prime of the form 2^n - 1',
        gradeLevel: 5,
      },
      {
        id: '91',
        text: 'If one ream of paper costs $7, how many reams can you buy for $98?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['11', '12', '13', '14'],
        correctAnswer: '14',
        gradeLevel: 5,
      },
      {
        id: '92',
        text: 'If the radius of a sphere is tripled, how does the volume change?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['Multiplies by 3', 'Multiplies by 9', 'Multiplies by 27', 'Multiplies by 81'],
        correctAnswer: 'Multiplies by 27',
        gradeLevel: 5,
      },
      {
        id: '93',
        text: 'What is the smallest composite number?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '3', '4', '5'],
        correctAnswer: '4',
        gradeLevel: 5,
      },
      {
        id: '94',
        text: 'If m + n = 25, what is the value of m + n + 8?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['31', '32', '33', '34'],
        correctAnswer: '33',
        gradeLevel: 5,
      },
      {
        id: '95',
        text: 'The height and base of a triangle are 20cm each what is the triangles area?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['100', '200', '300', '400'],
        correctAnswer: '200',
        gradeLevel: 5,
      },
      {
        id: '96',
        text: 'A 20 feet ladder rests against a wall 12 feet from the wall. How high up the wall will the ladder rest?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['14', '15', '16', '17'],
        correctAnswer: '16',
        gradeLevel: 5,
      },
      {
        id: '97',
        text: 'Average age of 3 children is 9 years. The ages of two of them are 8 years and 11 years. What is the age of the third child?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['6', '7', '8', '9'],
        correctAnswer: '8',
        gradeLevel: 5,
      },
      {
        id: '98',
        text: 'What is a Fibonacci Sequence?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['Sum of Previous number', 'Product of Previous 2 numbers', 'Sum of Previous 2 numbers', 'Product of Previous number'],
        correctAnswer: 'Sum of Previous 2 numbers',
        gradeLevel: 5,
      },
      {
        id: '99',
        text: 'If a train covers 195 miles in 3 hours, what is the average speed of the train?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['55', '60', '65', '70'],
        correctAnswer: '65',
        gradeLevel: 5,
      },
      {
        id: '100',
        text: 'An article costs $495 with a 10% sales tax on it. How much will the article cost after the taxes are applied?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$540.5', '$542.5', '$544.5', '$546.5'],
        correctAnswer: '$544.5',
        gradeLevel: 5,
      },
    ],
  },
  {
    id: '101',
    title: 'Math - Algebraic Expressions',
    category: 'Math',
    type: 'Normal',
    explanation: 'Simplifying and evaluating algebraic expressions.',
    questions: [
      {
        id: '4',
        text: 'Solve for x: 2x + 5 = 15',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '4', '5', '6'],
        correctAnswer: '5',
        gradeLevel: 4,
      },
      {
        id: '5',
        text: 'Simplify: 3(a + 2b) - a + b',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2a + 7b', '2a + 6b', '3a + 7b', '3a + 6b'],
        correctAnswer: '2a + 7b',
        gradeLevel: 5,
      },
      {
        id: '6',
        text: 'If x = 3 and y = 4, what is the value of x^2 + y^2?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['7', '49', '25', '14'],
        correctAnswer: '25',
        gradeLevel: 5,
      },
      {
        id: '7',
        text: 'If 4(2x - 3) = 36, what is the value of x?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '6', '9', '12'],
        correctAnswer: '6',
        gradeLevel: 5,
      },
      {
        id: '8',
        text: 'Solve for a: 5a + 3 = 2a + 15',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '4',
        gradeLevel: 4,
      },
      {
        id: '9',
        text: 'Simplify: 4m - 2(3 - m)',
        category: 'Math',
        type: 'multiple-choice',
        options: ['6m - 6', '6m + 6', '2m - 6', '2m + 6'],
        correctAnswer: '6m - 6',
        gradeLevel: 5,
      },
      {
        id: '10',
        text: 'Evaluate: (2x + 3y) / (x - y) when x = 4 and y = 2',
        category: 'Math',
        type: 'multiple-choice',
        options: ['7', '11', '14', '22'],
        correctAnswer: '14',
        gradeLevel: 5,
      },
      {
        id: '11',
        text: 'Solve for y: 3(y + 5) - 2 = 25',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '4',
        gradeLevel: 4,
      },
      {
        id: '12',
        text: 'What is the value of p in the equation 2p - 8 = 0?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '4',
        gradeLevel: 4,
      },
      {
        id: '13',
        text: 'Solve for x in the equation 5x + 3 = 18',
        category: 'Math',
        type: 'multiple-choice',
        options: ['1', '3', '5', '7'],
        correctAnswer: '3',
        gradeLevel: 4,
      },
      {
        id: '14',
        text: 'If 2x - 1 = 9, what is the value of x?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '5',
        gradeLevel: 5,
      },
      {
        id: '15',
        text: 'Solve for y: 4y + 3(y - 2) = 8',
        category: 'Math',
        type: 'multiple-choice',
        options: ['1', '2', '3', '4'],
        correctAnswer: '2',
        gradeLevel: 5,
      },
      {
        id: '16',
        text: 'Find x if 3(x + 2) = 15',
        category: 'Math',
        type: 'multiple-choice',
        options: ['1', '3', '5', '7'],
        correctAnswer: '3',
        gradeLevel: 4,
      },
      {
        id: '17',
        text: 'Solve for y in the equation 2(y - 1) = 8',
        category: 'Math',
        type: 'multiple-choice',
        options: ['1', '3', '5', '7'],
        correctAnswer: '5',
        gradeLevel: 5,
      },
      {
        id: '18',
        text: 'If 5x + 2 = 17, what is x?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['1', '3', '5', '7'],
        correctAnswer: '3',
        gradeLevel: 5,
      },
      {
        id: '19',
        text: 'Solve: 2a + 3 = a + 7',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '4',
        gradeLevel: 4,
      },
      {
        id: '20',
        text: 'Simplify: 4(x - 2) + 5x = 28',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '4',
        gradeLevel: 5,
      },
      {
        id: '21',
        text: 'If a/3 - 1 = 5, find a',
        category: 'Math',
        type: 'multiple-choice',
        options: ['12', '18', '24', '30'],
        correctAnswer: '18',
        gradeLevel: 5,
      },
      {
        id: '22',
        text: 'Solve for p in the equation 3p - 7 = 20',
        category: 'Math',
        type: 'multiple-choice',
        options: ['5', '7', '9', '11'],
        correctAnswer: '9',
        gradeLevel: 5,
      },
      {
        id: '23',
        text: 'What is the value of x if 4x + 2 = 22?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '5',
        gradeLevel: 4,
      },
      {
        id: '24',
        text: 'Solve for m: 2(m + 1) = 16',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '7',
        gradeLevel: 5,
      },
      {
        id: '25',
        text: 'Given 5x - 10 = 25, what is x?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '7',
        gradeLevel: 5,
      },
      {
        id: '26',
        text: 'Find x in the equation 3x - 5 = 16',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '7',
        gradeLevel: 5,
      },
      {
        id: '27',
        text: 'If 4(y + 2) = 24, what is the value of y?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '4',
        gradeLevel: 4,
      },
      {
        id: '28',
        text: 'Solve for a in the equation 2a + 7 = 19',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '6', '7'],
        correctAnswer: '6',
        gradeLevel: 5,
      },
      {
        id: '29',
        text: 'If 3x + 5 = 26, what is x equal to?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '7',
        gradeLevel: 5,
      },
      {
        id: '30',
        text: 'Solve for p: 6p - 12 = 36',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '8',
        gradeLevel: 4,
      },
      {
        id: '31',
        text: 'Find the value of x in the equation 7x - 14 = 0',
        category: 'Math',
        type: 'multiple-choice',
        options: ['0', '2', '4', '6'],
        correctAnswer: '2',
        gradeLevel: 4,
      },
      {
        id: '32',
        text: 'Solve for m in the equation 5m + 3 = 23',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '4',
        gradeLevel: 5,
      },
      {
        id: '33',
        text: 'If 2(x + 3) = 14, then x = ?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '4',
        gradeLevel: 4,
      },
      {
        id: '34',
        text: 'Solve for y: 4y - 8 = 12',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '5',
        gradeLevel: 5,
      },
      {
        id: '35',
        text: 'If 3(a - 2) = 18, find a',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '8',
        gradeLevel: 4,
      },
      {
        id: '36',
        text: 'Solve for p: 2p + 5 = 15',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '5',
        gradeLevel: 5,
      },
      {
        id: '37',
        text: 'What is the value of x if 6x - 9 = 21?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '5',
        gradeLevel: 5,
      },
      {
        id: '38',
        text: 'Solve for m in the equation 5m + 10 = 45',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '7'],
        correctAnswer: '7',
        gradeLevel: 5,
      },
      {
        id: '39',
        text: 'If 2(x - 3) = 10, then x = ?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '8',
        gradeLevel: 4,
      },
      {
        id: '40',
        text: 'Solve for y: 4y + 5 = 25',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '5',
        gradeLevel: 5,
      },
      {
        id: '41',
        text: 'Solve for x: 3x + 7 = 19',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '4',
        gradeLevel: 4,
      },
      {
        id: '42',
        text: 'If 5y - 4 = 21, what is the value of y?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '5',
        gradeLevel: 5,
      },
      {
        id: '43',
        text: 'What is the solution to 2(a + 3) = 16?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '5',
        gradeLevel: 5,
      },
      {
        id: '44',
        text: 'Find the value of m in the equation 3m - 11 = 19',
        category: 'Math',
        type: 'multiple-choice',
        options: ['4', '6', '8', '10'],
        correctAnswer: '10',
        gradeLevel: 4,
      },
      {
        id: '45',
        text: 'If 4p + 2 = 30, solve for p',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '5', '7', '9'],
        correctAnswer: '7',
        gradeLevel: 5,
      },
      {
        id: '46',
        text: 'Solve for a in the equation 6a - 4 = 32',
        category: 'Math',
        type: 'multiple-choice',
        options: ['4', '6', '8', '10'],
        correctAnswer: '6',
        gradeLevel: 4,
      },
      {
        id: '47',
        text: 'What is the result when solving for x: 3x + 6 = 42?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['8', '10', '12', '14'],
        correctAnswer: '12',
        gradeLevel: 5,
      },
      {
        id: '48',
        text: 'If 5y + 3 = 48, what is y equal to?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['7', '9', '11', '13'],
        correctAnswer: '9',
        gradeLevel: 5,
      },
      {
        id: '49',
        text: 'Solve for p: 2(p - 5) = 24',
        category: 'Math',
        type: 'multiple-choice',
        options: ['13', '15', '17', '19'],
        correctAnswer: '17',
        gradeLevel: 5,
      },
      {
        id: '50',
        text: 'What is the value of x if 7x - 12 = 47?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['5', '7', '9', '11'],
        correctAnswer: '9',
        gradeLevel: 5,
      },
      {
        id: '51',
        text: 'Solve for y: 9y + 15 = 69',
        category: 'Math',
        type: 'multiple-choice',
        options: ['4', '5', '6', '7'],
        correctAnswer: '6',
        gradeLevel: 5,
      },
      {
        id: '52',
        text: 'What is the value of z, given 2z - 5 = 31?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['12', '14', '16', '18'],
        correctAnswer: '18',
        gradeLevel: 5,
      },
      {
        id: '53',
        text: 'Find the missing number: 3(x + 7) = 57',
        category: 'Math',
        type: 'multiple-choice',
        options: ['10', '12', '14', '16'],
        correctAnswer: '12',
        gradeLevel: 5,
      },
      {
        id: '54',
        text: 'What is the value of x in the equation 12x - 10 = 134?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['10', '12', '14', '16'],
        correctAnswer: '12',
        gradeLevel: 5,
      },
      {
        id: '55',
        text: 'Given 2a + 4 = 38, what is the value of a?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['13', '15', '17', '19'],
        correctAnswer: '17',
        gradeLevel: 5,
      },
      {
        id: '56',
        text: 'Solve for x: 5x + 14 = 64',
        category: 'Math',
        type: 'multiple-choice',
        options: ['6', '8', '10', '12'],
        correctAnswer: '10',
        gradeLevel: 5,
      },
      {
        id: '57',
        text: 'Find x in the equation 4(x - 3) = 32',
        category: 'Math',
        type: 'multiple-choice',
        options: ['7', '9', '11', '13'],
        correctAnswer: '11',
        gradeLevel: 5,
      },
      {
        id: '58',
        text: 'The perimeter of a rectangle is represented by P = 2L + 2W, where P = 80 and L = 22. Solve for W',
        category: 'Math',
        type: 'multiple-choice',
        options: ['16', '18', '20', '22'],
        correctAnswer: '18',
        gradeLevel: 5,
      },
      {
        id: '59',
        text: 'A triangle has angles A, B, and C. If angle A = 52 degrees and angle B = 81 degrees, find angle C',
        category: 'Math',
        type: 'multiple-choice',
        options: ['45', '47', '49', '51'],
        correctAnswer: '47',
        gradeLevel: 5,
      },
      {
        id: '60',
        text: 'What is the surface area of the sphere?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['πr²', '4πr²', '5πr²', '2πr'],
        correctAnswer: '4πr²',
        gradeLevel: 5,
      },
      {
        id: '61',
        text: '2/3(x + 5) = 40, what is x?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['45', '50', '55', '60'],
        correctAnswer: '55',
        gradeLevel: 5,
      },
      {
        id: '62',
        text: 'Solve for b : 2b + 8 = 20',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2', '4', '6', '8'],
        correctAnswer: '6',
        gradeLevel: 5,
      },
      {
        id: '63',
        text: 'If x = 6, what is x squared + 5x - 10?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['36', '56', '66', '76'],
        correctAnswer: '56',
        gradeLevel: 5,
      },
      {
        id: '64',
        text: 'What is the simplified version of a + a + b +b + b?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['4a+2b', '2a+3b', '3a +3b', '10 ab'],
        correctAnswer: '2a + 3b',
        gradeLevel: 5,
      },
      {
        id: '65',
        text: 'What is the x is 5x + 22 -x = 54?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['4', '6', '8', '10'],
        correctAnswer: '8',
        gradeLevel: 5,
      },
      {
        id: '66',
        text: 'If 2x+3 = 5x-11, solve for x',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '13/3', '14/3', '15/3'],
        correctAnswer: '14/3',
        gradeLevel: 5,
      },
      {
        id: '67',
        text: 'What is the simplified form of  (3x+5y)+(4x-6y)?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['7x+y', '7x-y', '7xy', 'x+7y'],
        correctAnswer: '7x - y',
        gradeLevel: 5,
      },
      {
        id: '68',
        text: 'What is the answer for a in  4(a+3)=36?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['4', '5', '6', '7'],
        correctAnswer: '6',
        gradeLevel: 5,
      },
      {
        id: '69',
        text: 'What does x = in 3x + 11 = 56',
        category: 'Math',
        type: 'multiple-choice',
        options: ['11', '13', '15', '17'],
        correctAnswer: '15',
        gradeLevel: 5,
      },
      {
        id: '70',
        text: 'Solve for x: 5x^2 + 20 = 45.',
        category: 'Math',
        type: 'multiple-choice',
        options: ['±√3', '±√5', '±3', '±5'],
        correctAnswer: '±√5',
        gradeLevel: 5,
      },
      {
        id: '71',
        text: 'Simplify: 4y - 2(3 - y)',
        category: 'Math',
        type: 'multiple-choice',
        options: ['14y - 6', '6y + 6', '6y - 6', '4y - 6'],
        correctAnswer: '6y - 6',
        gradeLevel: 5,
      },
      {
        id: '72',
        text: 'if y = -1, what does 2y^3 + 4y^2 - 3y + 7 =?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['10', '12', '14', '16'],
        correctAnswer: '12',
        gradeLevel: 5,
      },
      {
        id: '73',
        text: 'What would b be if 6b + 3(2b-1) = 9?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['0', '1', '2', '3'],
        correctAnswer: '1',
        gradeLevel: 5,
      },
      {
        id: '74',
        text: 'What is a polynomial?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['Expression with variables', 'Expression with variables numbers', 'Expression with constants and variables', 'Expression with equations'],
        correctAnswer: 'Expression with constants and variables',
        gradeLevel: 5,
      },
      {
        id: '75',
        text: 'Solve for w, |w - 5| = 3',
        category: 'Math',
        type: 'multiple-choice',
        options: ['1,2', '2,8', '1,3', '3, 7'],
        correctAnswer: '2, 8',
        gradeLevel: 5,
      },
      {
        id: '76',
        text: 'Solve for z: 3z - 14 = 28',
        category: 'Math',
        type: 'multiple-choice',
        options: ['12', '13', '14', '15'],
        correctAnswer: '14',
        gradeLevel: 5,
      },
      {
        id: '77',
        text: 'A+B = 10, B+C = 20. What does C-A =?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['10', '11', '12', '13'],
        correctAnswer: '10',
        gradeLevel: 5,
      },
      {
        id: '78',
        text: 'If a book store sold x number of books in one year and 2x + 10 books in another year. If x=30 what is the total of books that was sold?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['80', '90', '100', '110'],
        correctAnswer: '100',
        gradeLevel: 5,
      },
      {
        id: '79',
        text: 'If the perimeter of an equlateral triangle is 90cm what is each side measuring as?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['10', '20', '30', '40'],
        correctAnswer: '30',
        gradeLevel: 5,
      },
      {
        id: '80',
        text: 'if 3/5 x - 7 = 2 what is x?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['15', '16', '17', '18'],
        correctAnswer: '15',
        gradeLevel: 5,
      },
      {
        id: '81',
        text: 'What does a equal if a=4b^2 and b =3?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['16', '26', '36', '46'],
        correctAnswer: '36',
        gradeLevel: 5,
      },
      {
        id: '82',
        text: 'If x/5 + 7 = 12, what is x?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['5', '15', '25', '35'],
        correctAnswer: '25',
        gradeLevel: 5,
      },
      {
        id: '83',
        text: 'Simplify 4(x+6) / 8.',
        category: 'Math',
        type: 'multiple-choice',
        options: ['x/2 + 6', '(x + 6) / 2', 'x+2/6', 'x/3 + 6'],
        correctAnswer: '(x + 6) / 2',
        gradeLevel: 5,
      },
      {
        id: '84',
        text: 'What is a quadratic equation?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['An equation where the highest exponent is three', 'An equation where the highest exponent is one', 'An equation where the highest exponent is four', 'An equation where the highest exponent is two'],
        correctAnswer: 'An equation where the highest exponent is two',
        gradeLevel: 5,
      },
      {
        id: '85',
        text: 'If x^2 = 64, what is x',
        category: 'Math',
        type: 'multiple-choice',
        options: ['5', '6', '7', '8'],
        correctAnswer: '8',
        gradeLevel: 5,
      },
      {
        id: '86',
        text: 'Simplify: a(b+c)',
        category: 'Math',
        type: 'multiple-choice',
        options: ['ab+ac', 'a+b+c', 'ac+bc', 'ab+bc'],
        correctAnswer: 'ab+ac',
        gradeLevel: 5,
      },
      {
        id: '87',
        text: 'Which equation has a solution of x = 3',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3x + 5 = 11', '3x + 5 = 12', '3x + 5 = 13', '3x + 5 = 14'],
        correctAnswer: '3x + 5 = 14',
        gradeLevel: 5,
      },
      {
        id: '88',
        text: 'What is 3a^3 + 3a + 33a^2 if a is 1?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['37', '38', '39', '40'],
        correctAnswer: '39',
        gradeLevel: 5,
      },
      {
        id: '89',
        text: 'If 2a - 8 = -2, solve for a',
        category: 'Math',
        type: 'multiple-choice',
        options: ['1', '2', '3', '4'],
        correctAnswer: '3',
        gradeLevel: 5,
      },
      {
        id: '90',
        text: 'The sides of a triangle is a, b, c what will the perimeter be',
        category: 'Math',
        type: 'multiple-choice',
        options: ['ab+bc', 'a+b+c', 'abc', 'a/b/c'],
        correctAnswer: 'a + b + c',
        gradeLevel: 5,
      },
      {
        id: '91',
        text: 'If the ratio of two supplementary angles is 2:3, what is the measure of the smaller angle?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['70', '71', '72', '73'],
        correctAnswer: '72',
        gradeLevel: 5,
      },
      {
        id: '92',
        text: 'Simplify and express with positive exponents: (x^−2)(y^3)',
        category: 'Math',
        type: 'multiple-choice',
        options: ['x^2/y^3', 'y^3/x^2', 'x^2 y^3', 'xy'],
        correctAnswer: 'y^3 / x^2',
        gradeLevel: 5,
      },
      {
        id: '93',
        text: 'Factor completely: 16 - x^2',
        category: 'Math',
        type: 'multiple-choice',
        options: ['(4 + x)(4 + x)', '(4 - x)(4-x)', '(4 + x)(4 - x)', '(4+x)(4+y)'],
        correctAnswer: '(4 + x)(4 - x)',
        gradeLevel: 5,
      },
      {
        id: '94',
        text: 'Find the sum of the roots of the quadratic equation x^2 + 5x + 6 = 0',
        category: 'Math',
        type: 'multiple-choice',
        options: ['-4', '-5', '-6', '-7'],
        correctAnswer: '-5',
        gradeLevel: 5,
      },
      {
        id: '95',
        text: 'Solve the inequality for x: 3x + 5 &lt; 14',
        category: 'Math',
        type: 'multiple-choice',
        options: ['x > 3', 'x = 3', 'x &lt; 3', 'x + 3'],
        correctAnswer: 'x &lt; 3',
        gradeLevel: 5,
      },
      {
        id: '96',
        text: 'How do you calculate the circumference of a circle?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['πd or 2πr', 'πd', '3πd', '5πd'],
        correctAnswer: 'πd or 2πr',
        gradeLevel: 5,
      },
      {
        id: '97',
        text: 'The sides of a triangle are in ratio of 3:4:5 what kind of triangle is this?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['Eqilateral', 'Isosceles', 'Right angle triangle', 'Scalene'],
        correctAnswer: 'Right angle triangle',
        gradeLevel: 5,
      },
      {
        id: '98',
        text: 'What does a co-efficient mean?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['Number in front of a variable', 'A expression', 'Constant', 'Polynomial'],
        correctAnswer: 'Number in front of a variable',
        gradeLevel: 5,
      },
      {
        id: '99',
        text: 'If a rectangle is 10 by 14 what is the area',
        category: 'Math',
        type: 'multiple-choice',
        options: ['120', '130', '140', '150'],
        correctAnswer: '140',
        gradeLevel: 5,
      },
      {
        id: '100',
        text: 'What does area mean?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['Measurement of a line', 'Measurement of a curve', 'Measurement of a angle', 'Measurement of a surface'],
        correctAnswer: 'Measurement of a surface',
        gradeLevel: 5,
      },
    ],
  },
  {
    id: '2',
    title: 'Math - Word Problems',
    category: 'Math',
    type: 'Word',
    explanation: 'Applying math skills to solve real-world problems.',
    questions: [
      {
        id: '1',
        text: 'John has 15 apples. He gives 7 apples to his friend. How many apples does John have left?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['6', '7', '8', '9'],
        correctAnswer: '8',
        gradeLevel: 4,
      },
      {
        id: '2',
        text: 'A farmer has 24 cows. If he divides them equally into 3 groups, how many cows are in each group?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['6', '7', '8', '9'],
        correctAnswer: '8',
        gradeLevel: 4,
      },
      {
        id: '3',
        text: 'Sarah buys a book for $8 and a pen for $3. How much money does she spend in total?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$9', '$10', '$11', '$12'],
        correctAnswer: '$11',
        gradeLevel: 4,
      },
      {
        id: '4',
        text: 'A train travels 120 miles in 2 hours. What is its average speed?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['50', '60', '70', '80'],
        correctAnswer: '60',
        gradeLevel: 5,
      },
      {
        id: '5',
        text: 'A rectangle has a length of 10 cm and a width of 6 cm. What is its area?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['30', '40', '50', '60'],
        correctAnswer: '60',
        gradeLevel: 5,
      },
      {
        id: '6',
        text: 'Tom has 3 bags of marbles. Each bag contains 9 marbles. How many marbles does Tom have in all?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['17', '19', '27', '29'],
        correctAnswer: '27',
        gradeLevel: 4,
      },
      {
        id: '7',
        text: 'A pizza is cut into 8 slices. If you eat 3 slices, how many slices are left?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '4', '5', '6'],
        correctAnswer: '5',
        gradeLevel: 4,
      },
      {
        id: '8',
        text: 'A school has 150 students. If 60 students are girls, how many students are boys?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['70', '80', '90', '100'],
        correctAnswer: '90',
        gradeLevel: 4,
      },
      {
        id: '9',
        text: 'A baker makes 40 cookies. He sells 28 cookies. How many cookies are left?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['10', '11', '12', '13'],
        correctAnswer: '12',
        gradeLevel: 4,
      },
      {
        id: '10',
        text: 'A garden has 5 rows of flowers. Each row has 12 flowers. How many flowers are in the garden?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['50', '60', '70', '80'],
        correctAnswer: '60',
        gradeLevel: 5,
      },
      {
        id: '11',
        text: 'If a shirt costs $25 and you pay with a $50 bill, how much change do you receive?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$22', '$23', '$24', '$25'],
        correctAnswer: '$25',
        gradeLevel: 5,
      },
      {
        id: '12',
        text: 'A library has 1000 books. 345 books are borrowed. How many books are left in the library?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['655', '755', '855', '955'],
        correctAnswer: '655',
        gradeLevel: 5,
      },
      {
        id: '13',
        text: 'A movie starts at 7:30 PM and ends at 9:15 PM. How long is the movie?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['1 hour 35 minutes', '1 hour 45 minutes', '1 hour 55 minutes', '2 hours 5 minutes'],
        correctAnswer: '1 hour 45 minutes',
        gradeLevel: 5,
      },
      {
        id: '14',
        text: 'If you drive 300 miles at a speed of 60 mph, how long will the trip take?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '4', '5', '6'],
        correctAnswer: '5',
        gradeLevel: 5,
      },
      {
        id: '15',
        text: 'A store sells a product for $45, which includes a 20% markup. What was the original cost of the product?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$36', '$37.5', '$40', '$42.5'],
        correctAnswer: '$37.5',
        gradeLevel: 5,
      },
      {
        id: '16',
        text: 'A class has 25 students. Each student needs 2 pencils. How many pencils are needed in total?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['30', '40', '50', '60'],
        correctAnswer: '50',
        gradeLevel: 5,
      },
      {
        id: '17',
        text: 'A farmer plants 8 rows of apple trees. Each row has 15 trees. How many apple trees did he plant?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['100', '110', '120', '130'],
        correctAnswer: '120',
        gradeLevel: 5,
      },
      {
        id: '18',
        text: 'A water tank contains 500 liters of water. 185 liters are used. How many liters are left in the tank?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['315', '325', '335', '345'],
        correctAnswer: '315',
        gradeLevel: 5,
      },
      {
        id: '19',
        text: 'A store sells a TV for $350 and a DVD player for $75. How much will both items cost?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$400', '$415', '$425', '$435'],
        correctAnswer: '$425',
        gradeLevel: 5,
      },
      {
        id: '20',
        text: 'A car travels 450 km in 5 hours. What is the average speed of the car?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['70', '80', '90', '100'],
        correctAnswer: '90',
        gradeLevel: 5,
      },
      {
        id: '21',
        text: 'John has 25 marbles, and Tom has 18 marbles. How many marbles do they have altogether?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['40', '41', '42', '43'],
        correctAnswer: '43',
        gradeLevel: 4,
      },
      {
        id: '22',
        text: 'Sarah has 35 stickers. She gives 12 stickers to her friend. How many stickers does Sarah have left?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['21', '22', '23', '24'],
        correctAnswer: '23',
        gradeLevel: 4,
      },
      {
        id: '23',
        text: 'A baker makes 48 cupcakes. She divides them equally into 6 boxes. How many cupcakes are in each box?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['6', '7', '8', '9'],
        correctAnswer: '8',
        gradeLevel: 4,
      },
      {
        id: '24',
        text: 'A train travels 240 miles in 4 hours. What is the average speed of the train?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['50', '60', '70', '80'],
        correctAnswer: '60',
        gradeLevel: 5,
      },
      {
        id: '25',
        text: 'A class has 30 students. If 2/5 of the students are girls, how many girls are there in the class?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['10', '11', '12', '13'],
        correctAnswer: '12',
        gradeLevel: 5,
      },
      {
        id: '26',
        text: 'If one apple costs $0.75, how much will 8 apples cost?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$4', '$5', '$6', '$7'],
        correctAnswer: '$6',
        gradeLevel: 5,
      },
      {
        id: '27',
        text: 'A garden is 15 meters long and 8 meters wide. What is the perimeter of the garden?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['40', '42', '44', '46'],
        correctAnswer: '46',
        gradeLevel: 5,
      },
      {
        id: '28',
        text: 'A pizza is cut into 12 slices. If you eat 1/4 of the pizza, how many slices did you eat?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['3', '4', '5', '6'],
        correctAnswer: '3',
        gradeLevel: 5,
      },
      {
        id: '29',
        text: 'A student scores 80 out of 100 on a test. What percentage did the student get?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['60', '70', '80', '90'],
        correctAnswer: '80',
        gradeLevel: 5,
      },
      {
        id: '30',
        text: 'A store is selling pencils for $0.50 each. If you buy 6 pencils, how much will it cost?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$1', '$2', '$3', '$4'],
        correctAnswer: '$3',
        gradeLevel: 5,
      },
      {
        id: '31',
        text: 'A school has 450 students. If 1/3 of the students are in the primary section, how many students are in the primary section?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['50', '100', '150', '200'],
        correctAnswer: '150',
        gradeLevel: 5,
      },
      {
        id: '32',
        text: 'A book has 320 pages. If you read 40 pages each day, how many days will it take to finish the book?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['6', '7', '8', '9'],
        correctAnswer: '8',
        gradeLevel: 5,
      },
      {
        id: '33',
        text: 'A box contains 36 chocolates. If 4 children share the chocolates equally, how many chocolates does each child get?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['6', '7', '8', '9'],
        correctAnswer: '9',
        gradeLevel: 4,
      },
      {
        id: '34',
        text: 'If a train travels at a speed of 75 miles per hour, how far will it travel in 3 hours?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['200', '225', '250', '275'],
        correctAnswer: '225',
        gradeLevel: 5,
      },
      {
        id: '35',
        text: 'A rectangular garden is 20 feet long and 12 feet wide. What is its area?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['230', '235', '240', '250'],
        correctAnswer: '240',
        gradeLevel: 5,
      },
      {
        id: '36',
        text: 'A group of friends went to the movies. Tickets cost $8.50 each, and they bought 5 tickets. What was the total cost?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$40.5', '$41', '$41.5', '$42.5'],
        correctAnswer: '$42.5',
        gradeLevel: 5,
      },
      {
        id: '37',
        text: 'A store sells apples for $1.25 each. If you buy 10 apples, how much will it cost?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$11.5', '$12', '$12.5', '$13'],
        correctAnswer: '$12.5',
        gradeLevel: 5,
      },
      {
        id: '38',
        text: 'A bus travels 180 miles in 3 hours. What is its average speed?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['40', '50', '60', '70'],
        correctAnswer: '60',
        gradeLevel: 5,
      },
      {
        id: '39',
        text: 'A school has 600 students, and 45% of them are girls. How many boys are there in the school?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['300', '320', '330', '340'],
        correctAnswer: '330',
        gradeLevel: 5,
      },
      {
        id: '40',
        text: 'If you save $25 each week, how much money will you save in 12 weeks?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$100', '$200', '$300', '$400'],
        correctAnswer: '$300',
        gradeLevel: 5,
      },
      {
        id: '41',
        text: 'The price of a pen is $2.00 and the price of a book is $15. If you buy one pen and one book, what is the total cost?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$14', '$15', '$16', '$17'],
        correctAnswer: '$17',
        gradeLevel: 5,
      },
      {
        id: '42',
        text: 'John has 34 pencils and Peter has 47 pencils. How many more pencils does Peter have than John?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['13', '14', '15', '16'],
        correctAnswer: '13',
        gradeLevel: 5,
      },
      {
        id: '43',
        text: 'A teacher divides 96 students into groups of 8. How many groups are there?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['10', '11', '12', '13'],
        correctAnswer: '12',
        gradeLevel: 4,
      },
      {
        id: '44',
        text: 'A shopkeeper sells 340 apples, 234 bananas and 121 mangoes in a day. How many fruits were sold in a day?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['685', '695', '705', '715'],
        correctAnswer: '695',
        gradeLevel: 4,
      },
      {
        id: '45',
        text: 'There are 1275 red roses in a garden, 2345 yellow roses and 987 white roses. How many roses are there in all?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['4507', '4607', '4707', '4807'],
        correctAnswer: '4607',
        gradeLevel: 4,
      },
      {
        id: '46',
        text: 'John buys a toy for $25.00, a book for $35.00 and a pen for $2.00 How much money did he spend altogether?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$52', '$62', '$72', '$82'],
        correctAnswer: '$62',
        gradeLevel: 4,
      },
      {
        id: '47',
        text: 'A class library has 234 story books, 145 science books and 23 history books. How many books are there in the class library?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['392', '402', '412', '422'],
        correctAnswer: '402',
        gradeLevel: 4,
      },
      {
        id: '48',
        text: 'A school has 1234 boys and 1345 girls. How many students are there in the school?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['2579', '2679', '2779', '2879'],
        correctAnswer: '2579',
        gradeLevel: 4,
      },
      {
        id: '49',
        text: 'An Ice cream vendor sold 23 ice creams on Monday, 45 ice creams on Tuesday and 2 ice creams on Wednesday. How many ice creams did the vendor sell in 3 days?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['60', '70', '80', '90'],
        correctAnswer: '70',
        gradeLevel: 4,
      },
      {
        id: '50',
        text: 'Peter buys a coke for $3.45, and a sandwich for $7.90. If he gives the shopkeeper a $20 note, how much change does he get back?',
        category: 'Math',
        type: 'multiple-choice',
        options: ['$8.65', '$9.65', '$10.65', '$11.65'],
        correctAnswer: '$8.65',
        gradeLevel: 5,
      },
    ],
  },
  {
    id: '3',
    title: 'Science - General Knowledge',
    category: 'Science',
    type: 'Normal',
    explanation: 'Test your general knowledge of science',
    questions: [
      {
        id: '51',
        text: 'Which gas do plants absorb from the atmosphere during photosynthesis?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
        correctAnswer: 'Carbon dioxide',
        gradeLevel: 4,
      },
      {
        id: '52',
        text: 'What is the basic unit of heredity?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Cell', 'Gene', 'Atom', 'Molecule'],
        correctAnswer: 'Gene',
        gradeLevel: 5,
      },
      {
        id: '53',
        text: 'What is the process by which water changes from a liquid to a gas?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Condensation', 'Evaporation', 'Freezing', 'Melting'],
        correctAnswer: 'Evaporation',
        gradeLevel: 4,
      },
      {
        id: '54',
        text: 'What is the function of the ozone layer?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Absorb UV radiation', 'Produce oxygen', 'Regulate temperature', 'Create clouds'],
        correctAnswer: 'Absorb UV radiation',
        gradeLevel: 5,
      },
      {
        id: '55',
        text: 'What is the name of the force that opposes motion between two surfaces in contact?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Gravity', 'Friction', 'Magnetism', 'Tension'],
        correctAnswer: 'Friction',
        gradeLevel: 4,
      },
      {
        id: '56',
        text: 'What is the term for the energy stored in an object due to its position?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Kinetic energy', 'Potential energy', 'Thermal energy', 'Chemical energy'],
        correctAnswer: 'Potential energy',
        gradeLevel: 5,
      },
      {
        id: '57',
        text: 'Which type of cell lacks a nucleus?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Eukaryotic', 'Prokaryotic', 'Stem cell', 'Blood cell'],
        correctAnswer: 'Prokaryotic',
        gradeLevel: 5,
      },
      {
        id: '58',
        text: 'What is the process by which cells divide to produce identical daughter cells?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Meiosis', 'Mitosis', 'Osmosis', 'Diffusion'],
        correctAnswer: 'Mitosis',
        gradeLevel: 5,
      },
      {
        id: '59',
        text: 'What is the primary function of red blood cells?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Fight infection', 'Oxygen transport', 'Blood clotting', 'Produce hormones'],
        correctAnswer: 'Oxygen transport',
        gradeLevel: 5,
      },
      {
        id: '60',
        text: 'What is the name of the vestigial organ in humans that is attached to the large intestine?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Gallbladder', 'Appendix', 'Spleen', 'Pancreas'],
        correctAnswer: 'Appendix',
        gradeLevel: 5,
      },
      {
        id: '61',
        text: 'What process do plant cells undergo to produce energy?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Photosynthesis', 'Cellular respiration', 'Transpiration', 'Osmosis'],
        correctAnswer: 'Cellular respiration',
        gradeLevel: 5,
      },
      {
        id: '62',
        text: 'Name the largest planet in our solar system',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Earth', 'Jupiter', 'Saturn', 'Neptune'],
        correctAnswer: 'Jupiter',
        gradeLevel: 4,
      },
      {
        id: '63',
        text: 'What is measured by an anemometer?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Air pressure', 'Temperature', 'Wind speed', 'Humidity'],
        correctAnswer: 'Wind speed',
        gradeLevel: 5,
      },
      {
        id: '64',
        text: 'What is the force that pulls objects towards each other?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Magnetism', 'Gravitation', 'Electricity', 'Tension'],
        correctAnswer: 'Gravitation',
        gradeLevel: 4,
      },
      {
        id: '65',
        text: 'What is the name of the process by which living organisms maintain a stable internal environment?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Evolution', 'Homeostasis', 'Adaptation', 'Respiration'],
        correctAnswer: 'Homeostasis',
        gradeLevel: 5,
      },
      {
        id: '66',
        text: 'What is the purpose of a control group in scientific experiments?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['To introduce bias', 'To test the hypothesis', 'Baseline for comparison', 'To create errors'],
        correctAnswer: 'Baseline for comparison',
        gradeLevel: 5,
      },
      {
        id: '67',
        text: 'What force opposes motion between two surfaces?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Electricity', 'Magnetism', 'Gravity', 'Friction'],
        correctAnswer: 'Friction',
        gradeLevel: 4,
      },
      {
        id: '68',
        text: 'Name the three states of matter.',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Solid, liquid, gas', 'Solid, liquid, plasma', 'Solid, liquid, energy', 'Solid, gas, energy'],
        correctAnswer: 'Solid, liquid, gas',
        gradeLevel: 4,
      },
      {
        id: '69',
        text: 'What is the name for a push or a pull?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Energy', 'Force', 'Power', 'Work'],
        correctAnswer: 'Force',
        gradeLevel: 4,
      },
      {
        id: '70',
        text: 'What is a biome?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['A type of cell', 'A type of rock', 'A large community of organisms and plants in an environment', 'A small community of organisms'],
        correctAnswer: 'A large community of organisms and plants in an environment',
        gradeLevel: 5,
      },
      {
        id: '71',
        text: 'What is a cell?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Basic unit of life', 'Basic unit of matter', 'Basic unit of energy', 'Basic unit of force'],
        correctAnswer: 'Basic unit of life',
        gradeLevel: 4,
      },
      {
        id: '72',
        text: 'What are the functions of the kidneys?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['To pump blood', 'To digest food', 'To filter the blood and produce urine', 'To produce hormones'],
        correctAnswer: 'To filter the blood and produce urine',
        gradeLevel: 5,
      },
      {
        id: '73',
        text: 'How are igneous rocks formed?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['From plant remains', 'From cooling magma or lava', 'From animal remains', 'From sediments'],
        correctAnswer: 'From cooling magma or lava',
        gradeLevel: 5,
      },
      {
        id: '74',
        text: 'What process do all living things perform to release energy from sugars?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Photosynthesis', 'Digestion', 'Cellular Respiration', 'Excretion'],
        correctAnswer: 'Cellular Respiration',
        gradeLevel: 5,
      },
      {
        id: '75',
        text: 'What is the name of our Galaxy?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Andromeda', 'Milky Way', 'Triangulum', 'Whirlpool'],
        correctAnswer: 'Milky Way',
        gradeLevel: 5,
      },
      {
        id: '76',
        text: 'What part of the human body makes insulin?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Liver', 'Pancreas', 'Stomach', 'Kidney'],
        correctAnswer: 'Pancreas',
        gradeLevel: 5,
      },
      {
        id: '77',
        text: 'What is the value of absolute zero in Celsius?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['-100', '-273.15', '0', '100'],
        correctAnswer: '-273.15',
        gradeLevel: 5,
      },
      {
        id: '78',
        text: 'What does metamorphosis mean?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Growth', 'Movement', 'Transformation', 'Change in weather'],
        correctAnswer: 'Transformation',
        gradeLevel: 4,
      },
      {
        id: '79',
        text: 'Which planet is closest to the sun?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Earth', 'Venus', 'Mercury', 'Mars'],
        correctAnswer: 'Mercury',
        gradeLevel: 4,
      },
      {
        id: '80',
        text: 'What is the chemical symbol for oxygen?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['C', 'H', 'N', 'O'],
        correctAnswer: 'O',
        gradeLevel: 4,
      },
      {
        id: '81',
        text: 'How many ventricles are in the human heart?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['1', '2', '3', '4'],
        correctAnswer: '2',
        gradeLevel: 5,
      },
      {
        id: '82',
        text: 'What name is given for the height of a wave?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Amplitude', 'Frequency', 'Wavelength', 'Speed'],
        correctAnswer: 'Amplitude',
        gradeLevel: 5,
      },
      {
        id: '83',
        text: 'The Earth is composed of four layers. Name them.',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Crust, mantle, outer core and inner core', 'Crust, mantle, core, atmosphere', 'Crust, hydrosphere, mantle, core', 'Crust, mantle, inner core, atmosphere'],
        correctAnswer: 'Crust, mantle, outer core and inner core',
        gradeLevel: 5,
      },
      {
        id: '84',
        text: 'What causes day and night?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Earths revolution', 'Earths tilt', 'Earths rotation', 'Sun’s revolution'],
        correctAnswer: 'Earths rotation',
        gradeLevel: 5,
      },
      {
        id: '85',
        text: 'How many vertebrae are in the human spinal column?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['23', '33', '43', '53'],
        correctAnswer: '33',
        gradeLevel: 5,
      },
      {
        id: '86',
        text: 'What system of measurement is typically used by scientists?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['The imperial system', 'The metric system', 'The English System', 'The binary system'],
        correctAnswer: 'The metric system',
        gradeLevel: 5,
      },
      {
        id: '87',
        text: 'Name the four main blood types.',
        category: 'Science',
        type: 'multiple-choice',
        options: ['A, B, C, O', 'A, B, AB, O', 'A, C, D, O', 'A, B, D, O'],
        correctAnswer: 'A, B, AB, O',
        gradeLevel: 5,
      },
      {
        id: '88',
        text: 'What is the name of the branch of science that studies plants?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Zoology', 'Botany', 'Ecology', 'Anatomy'],
        correctAnswer: 'Botany',
        gradeLevel: 5,
      },
      {
        id: '89',
        text: 'What is the name for a group of lions?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Herd', 'Pack', 'Pride', 'Group'],
        correctAnswer: 'Pride',
        gradeLevel: 4,
      },
      {
        id: '90',
        text: 'Which of the five senses develops first?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Sight', 'Hearing', 'Smell', 'Touch'],
        correctAnswer: 'Touch',
        gradeLevel: 4,
      },
      {
        id: '91',
        text: 'What is the biggest planet in our solar system?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Earth', 'Venus', 'Jupiter', 'Mars'],
        correctAnswer: 'Jupiter',
        gradeLevel: 4,
      },
      {
        id: '92',
        text: 'How many teeth does an adult human typically have?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['28', '30', '32', '34'],
        correctAnswer: '32',
        gradeLevel: 5,
      },
      {
        id: '93',
        text: 'What is the name for a baby frog?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Calf', 'Pup', 'Tadpole', 'Kid'],
        correctAnswer: 'Tadpole',
        gradeLevel: 4,
      },
      {
        id: '94',
        text: 'The Sun is mainly composed of which element?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Carbon', 'Oxygen', 'Hydrogen', 'Nitrogen'],
        correctAnswer: 'Hydrogen',
        gradeLevel: 5,
      },
      {
        id: '95',
        text: 'Name the three main types of rocks.',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Igneous, Earth, Sun', 'Igneous, Water, Metamorphic', 'Igneous, Sedimentary, Metamorphic', 'Sedimentary, Soil, Metamorphic'],
        correctAnswer: 'Igneous, Sedimentary, Metamorphic',
        gradeLevel: 5,
      },
      {
        id: '96',
        text: 'What are the phases of the moon?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['New, crescent, full', 'New, half, full', 'New, crescent, half, full', 'New, crescent, half, gibbous, full'],
        correctAnswer: 'New, crescent, half, gibbous, full',
        gradeLevel: 5,
      },
      {
        id: '97',
        text: 'What vitamin does the human body produce when exposed to the sun?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D'],
        correctAnswer: 'Vitamin D',
        gradeLevel: 5,
      },
      {
        id: '98',
        text: 'What is the name of a supercontinent that began breaking apart about 200 million years ago?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Atlantis', 'Lemuria', 'Pangaea', 'Gondwana'],
        correctAnswer: 'Pangaea',
        gradeLevel: 5,
      },
      {
        id: '99',
        text: 'Which blood type is the "universal donor?"',
        category: 'Science',
        type: 'multiple-choice',
        options: ['O positive', 'O negative', 'AB positive', 'AB negative'],
        correctAnswer: 'O negative',
        gradeLevel: 5,
      },
      {
        id: '100',
        text: 'Name the four seasons.',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Winter, Spring, Hot, Autumn', 'Spring, Summer, Rainy, Autumn', 'Winter, Spring, Summer, Autumn', 'Winter, Autumn, Sunny, Rainy'],
        correctAnswer: 'Winter, Spring, Summer, Autumn',
        gradeLevel: 4,
      },
      {
        id: '101',
        text: 'Which part of the body helps us think?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Heart', 'Brain', 'Lungs', 'Stomach'],
        correctAnswer: 'Brain',
        gradeLevel: 4,
      },
      {
        id: '102',
        text: 'What do we call a baby mouse?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Calf', 'Pup', 'Kid', 'Chick'],
        correctAnswer: 'Pup',
        gradeLevel: 4,
      },
      {
        id: '103',
        text: 'What is the name of a group of fish?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Pack', 'Herd', 'School', 'Pride'],
        correctAnswer: 'School',
        gradeLevel: 4,
      },
      {
        id: '104',
        text: 'What is the hardest substance in the human body?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Enamel', 'Bone', 'Cartilage', 'Ligament'],
        correctAnswer: 'Enamel',
        gradeLevel: 5,
      },
      {
        id: '105',
        text: 'Do butterflies have more than 4 legs?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Yes', 'No', 'Sometimes', 'Depends on species'],
        correctAnswer: 'Yes',
        gradeLevel: 4,
      },
      {
        id: '106',
        text: 'Do all birds fly?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Yes', 'No', 'Sometimes', 'Depends on species'],
        correctAnswer: 'No',
        gradeLevel: 4,
      },
      {
        id: '107',
        text: 'What part of the body pumps blood?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Heart', 'Brain', 'Lungs', 'Stomach'],
        correctAnswer: 'Heart',
        gradeLevel: 4,
      },
      {
        id: '108',
        text: 'Are humans mammals?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Yes', 'No', 'Sometimes', 'Depends on species'],
        correctAnswer: 'Yes',
        gradeLevel: 4,
      },
      {
        id: '109',
        text: 'What is the largest organ in the human body?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Heart', 'Brain', 'Skin', 'Liver'],
        correctAnswer: 'Skin',
        gradeLevel: 5,
      },
      {
        id: '110',
        text: 'How many arms does an octopus have?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Six', 'Seven', 'Eight', 'Nine'],
        correctAnswer: 'Eight',
        gradeLevel: 4,
      },
      {
        id: '111',
        text: 'What is the name of the biggest star we can see?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Sirius', 'Polaris', 'Vega', 'The Sun'],
        correctAnswer: 'The Sun',
        gradeLevel: 4,
      },
      {
        id: '112',
        text: 'What are the names of the four seasons',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Fall, Winter, spring, summer', 'Winter, Summer, Spring, fall', 'summer, Winter, spring, fall', 'Summer, Fall, Winter, spring'],
        correctAnswer: 'Fall, Winter, spring, summer',
        gradeLevel: 4,
      },
      {
        id: '113',
        text: 'Does all planets spin at the same speed?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['No', 'Yes', 'Spin', 'Rotation'],
        correctAnswer: 'No',
        gradeLevel: 4,
      },
      {
        id: '114',
        text: 'What do we call a scientist who studies fossils?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['A marine bilogist', 'A geologist', 'A paleontologist', 'A biologist'],
        correctAnswer: 'A paleontologist',
        gradeLevel: 4,
      },
      {
        id: '115',
        text: 'How many lungs do humans have?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['1', '2', '3', '4'],
        correctAnswer: '2',
        gradeLevel: 4,
      },
      {
        id: '116',
        text: 'How many bones does the average adult human have?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['206', '306', '406', '506'],
        correctAnswer: '206',
        gradeLevel: 4,
      },
      {
        id: '117',
        text: 'Is the Sun a planet or a star?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Star', 'Meteor', 'Moon', 'Planet'],
        correctAnswer: 'Star',
        gradeLevel: 4,
      },
      {
        id: '118',
        text: 'Which animal is known to have the most powerful bite on Earth?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Grizzly Bear', 'Saltwater Crocodile', 'Tiger', 'Hippo'],
        correctAnswer: 'Saltwater Crocodile',
        gradeLevel: 5,
      },
      {
        id: '119',
        text: ' What is the largest known structure in the universe?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['The Milky Way', 'Hercules-Corona Borealis Great Wall', 'The Solar System', 'The Oort Cloud'],
        correctAnswer: 'Hercules-Corona Borealis Great Wall',
        gradeLevel: 5,
      },
      {
        id: '120',
        text: ' What is the most abundant element in the Earth’s atmosphere?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Oxygen', 'Hydrogen', 'Carbon', 'Nitrogen'],
        correctAnswer: 'Nitrogen',
        gradeLevel: 5,
      },
      {
        id: '121',
        text: ' How many hearts does an octopus have?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['1', '2', '3', '4'],
        correctAnswer: '3',
        gradeLevel: 5,
      },
      {
        id: '122',
        text: ' What is the name of the largest ocean on Earth?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Atlantic', 'Pacific', 'Indian', 'Southern'],
        correctAnswer: 'Pacific',
        gradeLevel: 4,
      },
      {
        id: '123',
        text: ' How many legs does a spider have?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['6', '8', '10', '12'],
        correctAnswer: '8',
        gradeLevel: 4,
      },
      {
        id: '124',
        text: ' What part of the body protects our brain?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Skin', 'Skull', 'Vertebrae', 'Ribs'],
        correctAnswer: 'Skull',
        gradeLevel: 4,
      },
      {
        id: '125',
        text: 'What is the chemical symbol for salt?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Na', 'Cl', 'NaCl', 'H20'],
        correctAnswer: 'NaCl',
        gradeLevel: 5,
      },
      {
        id: '126',
        text: 'The name of the tallest tree species on Earth',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Sequoia sempervirens', 'Eucalyptus regnans', 'Redwood', 'Pinus'],
        correctAnswer: 'Sequoia sempervirens',
        gradeLevel: 5,
      },
      {
        id: '127',
        text: ' What is the name of the force that slows down or prevents movement between two objects',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Energy', 'Gravity', 'Motion', 'Friction'],
        correctAnswer: 'Friction',
        gradeLevel: 4,
      },
      {
        id: '128',
        text: ' Name the three states of matter',
        category: 'Science',
        type: 'multiple-choice',
        options: ['Solid, liquid, gas', 'Solid, gas, plasma', 'Liquid, solution, solid', 'Plasma, gas, vapor'],
        correctAnswer: 'Solid, liquid, gas',
        gradeLevel: 4,
      },
      {
        id: '129',
        text: 'A push or a pull is called',
        category: 'Science',
        type: 'multiple-choice',
        options: ['motion', 'energy', 'force', 'push'],
        correctAnswer: 'force',
        gradeLevel: 4,
      },
      {
        id: '130',
        text: ' The name of a scientist who studies plants is called a?',
        category: 'Science',
        type: 'multiple-choice',
        options: ['plantist', 'zoologist', 'biologist', 'botanist'],
        correctAnswer: 'botanist',
        gradeLevel: 4,
      },
    ],
  },
];

export default function Home() {
  const [selectedChapter, setSelectedChapter] = useState(chapters[0]);
  const [questionIndex, setQuestionIndex] = useState(0);
  const [currentQuestion, setCurrentQuestion] = useState(selectedChapter.questions[questionIndex]);
  const [studentAnswer, setStudentAnswer] = useState('');
  const [showHint, setShowHint] = useState(false);
  const [hint, setHint] = useState('');
  const {toast} = useToast();

  const getQuestionsForChapter = (chapter: any) => {
    return chapter.questions;
  };

  const validateAnswer = () => {
    if (studentAnswer === currentQuestion.correctAnswer) {
      toast({
        title: 'Correct!',
        description: 'Great job! Your answer is correct.',
      });
    } else {
      toast({
        title: 'Incorrect',
        description: `Keep trying! Your answer is not correct. The correct answer is ${currentQuestion.correctAnswer}.`,
      });
    }
  };

  const handleHintRequest = async () => {
    try {
      const hintResponse = await generateHint({
        question: currentQuestion.text,
        category: currentQuestion.category,
      });
      setHint(hintResponse.hint);
      setShowHint(true);
    } catch (error) {
      console.error('Error generating hint:', error);
      toast({
        title: 'Error',
        description: 'Failed to generate hint. Please try again.',
        variant: 'destructive',
      });
    }
  };

  const goToNextQuestion = () => {
    const questions = getQuestionsForChapter(selectedChapter);
    if (questionIndex < selectedChapter.questions.length - 1) {
      setQuestionIndex(questionIndex + 1);
      setCurrentQuestion(selectedChapter.questions[questionIndex + 1]);
      setStudentAnswer('');
      setShowHint(false);
    } else {
      toast({
        title: 'End of Chapter',
        description: 'You have reached the end of the chapter.',
      });
    }
  };

  const goToPreviousQuestion = () => {
    const questions = getQuestionsForChapter(selectedChapter);
    if (questionIndex > 0) {
      setQuestionIndex(questionIndex - 1);
      setCurrentQuestion(questions[questionIndex - 1]);
      setStudentAnswer('');
      setShowHint(false);
    } else {
      toast({
        title: 'Beginning of Chapter',
        description: 'You are at the beginning of the chapter.',
      });
    }
  };

  return (
    <SidebarProvider>
      <div className="flex h-screen">
        <Sidebar collapsible="icon">
          <SidebarHeader>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" className="gap-2 w-full justify-start px-2">
                  <Avatar className="h-8 w-8">
                    <AvatarImage src="https://picsum.photos/500/500" alt="Avatar"/>
                    <AvatarFallback>ZZ</AvatarFallback>
                  </Avatar>
                  <span>Olympiad Prep</span>
                  <Icons.chevronDown className="h-4 w-4 opacity-50"/>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" forceMount className="w-56">
                <DropdownMenuItem>
                  <ModeToggle/>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </SidebarHeader>
          <SidebarSeparator/>
          <SidebarContent>
            <SidebarGroup>
              <SidebarMenu>
                {chapters.map((chapter) => (
                  <SidebarMenuItem key={chapter.id}>
                    <SidebarMenuButton onClick={() => {
                      setSelectedChapter(chapter);
                      setQuestionIndex(0);
                      setCurrentQuestion(chapter.questions[0]);
                      setStudentAnswer('');
                      setShowHint(false);
                    }}>
                      {chapter.title}
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                ))}
              </SidebarMenu>
            </SidebarGroup>
          </SidebarContent>
          <SidebarFooter>
            <SidebarTrigger>
              <Button variant="outline" size="sm" className="w-full">
                <Icons.settings className="mr-2 h-4 w-4"/>
                Settings
              </Button>
            </SidebarTrigger>
          </SidebarFooter>
        </Sidebar>

        <div className="flex-1 p-4">
          <Card className="w-full h-full flex flex-col">
            <CardHeader>
              <CardTitle>{selectedChapter.title}</CardTitle>
              <CardDescription>Test your knowledge!</CardDescription>
            </CardHeader>
            <CardContent className="flex-1">
              <div className="mb-4">
                <p className="text-lg font-semibold">Question {questionIndex + 1} / {getQuestionsForChapter(selectedChapter).length}:</p>
                <p className="text-md">{currentQuestion.text}</p>
              </div>

              {currentQuestion.type === 'multiple-choice' ? (
                <RadioGroup defaultValue={studentAnswer} className="grid gap-2" onValueChange={setStudentAnswer}>
                  {currentQuestion.options.map((option) => (
                    <div key={option} className="flex items-center space-x-2">
                      <RadioGroupItem value={option} id={`r${option}`} className="text-primary" />
                      <Label htmlFor={`r${option}`}>{option}</Label>
                    </div>
                  ))}
                </RadioGroup>
              ) : (
                <div className="mb-4">
                  <Textarea
                    placeholder="Enter your answer"
                    className="w-full"
                    value={studentAnswer}
                    onChange={(e) => setStudentAnswer(e.target.value)}
                  />
                </div>
              )}
            </CardContent>
            <CardFooter className="flex justify-between">
              <Button onClick={validateAnswer}>Submit Answer</Button>
              <Button variant="secondary" onClick={handleHintRequest}>
                Get Hint
              </Button>
            </CardFooter>
            <CardFooter className="flex justify-between">
              <Button onClick={goToPreviousQuestion} disabled={questionIndex === 0}>
                Previous
              </Button>
              <Button onClick={goToNextQuestion} disabled={questionIndex === getQuestionsForChapter(selectedChapter).length - 1}>
                Next
              </Button>
            </CardFooter>
          </Card>
        </div>

      </div>

      {showHint && (
        <div className="fixed bottom-0 left-0 w-full bg-gray-100 p-4">
          <p>Hint: {hint}</p>
          <Button onClick={() => setShowHint(false)}>Close Hint</Button>
        </div>
      )}
    </SidebarProvider>
  );
}
